name: Generate Datas snake

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: emmnaa
          svg_out_path: dist/github-contribution-grid-snake.svg
